export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED';
export const INCREASE_COUNT_INGREDIENT: 'INCREASE_COUNT_INGREDIENT' = 'INCREASE_COUNT_INGREDIENT';
export const DECREASE_COUNT_INGREDIENT: 'DECREASE_COUNT_INGREDIENT' = 'DECREASE_COUNT_INGREDIENT';
export const UPDATE_COUNT_INGREDIENT: 'UPDATE_COUNT_INGREDIENT' = 'UPDATE_COUNT_INGREDIENT';
export const UPDATE_INGREDIENT_INFO: 'UPDATE_INGREDIENT_INFO' = 'UPDATE_INGREDIENT_INFO';
