export const WS_ORDERS_CONNECTION_START_AUTH: 'WS_ORDERS_CONNECTION_START_AUTH' = 'WS_ORDERS_CONNECTION_START_AUTH';
export const WS_ORDERS_CONNECTION_SUCCESS_AUTH: 'WS_ORDERS_CONNECTION_SUCCESS_AUTH' = 'WS_ORDERS_CONNECTION_SUCCESS_AUTH';
export const WS_ORDERS_CONNECTION_ERROR_AUTH: 'WS_ORDERS_CONNECTION_ERROR_AUTH' = 'WS_ORDERS_CONNECTION_ERROR_AUTH';
export const WS_ORDERS_GET_INFO_AUTH: 'WS_ORDERS_GET_INFO_AUTH' = 'WS_ORDERS_GET_INFO_AUTH';
export const WS_ORDERS_SEND_INFO_AUTH: 'WS_ORDERS_SEND_INFO_AUTH' = 'WS_ORDERS_SEND_INFO_AUTH';
export const WS_ORDERS_CONNECTION_CLOSED_AUTH: 'WS_ORDERS_CONNECTION_CLOSED_AUTH' = 'WS_ORDERS_CONNECTION_CLOSED_AUTH';
